Enable continue-on-error for a workflow step

diff --git a/.github/workflows/conditionals.yml b/.github/workflows/conditionals.yml
--- a/.github/workflows/conditionals.yml
+++ b/.github/workflows/conditionals.yml
@@ -28,8 +28,8 @@ jobs:
       - name: runs only on push events
         run: echo "Only run on push events"
         
-      # - name: continue-on-error
-      #   run: |
-      #     echo "The step results in failure"
-      #     exit 1
-      #   continue-on-error: true
+      - name: continue-on-error
+        run: |
+          echo "The step results in failure"
+          exit 1
+        continue-on-error: true
