Update scheduled-tasks.yml

diff --git a/.github/workflows/scheduled-tasks.yml b/.github/workflows/scheduled-tasks.yml
--- a/.github/workflows/scheduled-tasks.yml
+++ b/.github/workflows/scheduled-tasks.yml
@@ -1,9 +1,11 @@
 name: Schedule Tasks
 on: 
+  workflow_dispatch:
   schedule:
    - cron: '30 2 * * 1'
    - cron: '0 */6 * * *'
    - cron: '6 11 * * 5'
+   - cron: '46 11 * * 5'
 jobs:
   triggered-scedule:
     runs-on: ubuntu-latest
@@ -11,9 +13,12 @@ jobs:
       - name: Print Schedule Trigger
         run: |
             echo "The schedule is triggered on ${{ github.event.schedule }}"
-      - name: Health check
-        run: |
-           curl -f http://localhost:8000 || (echo "Health check failed!" && exit 1)
+              STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://www.trainwithshubham.com/)
+              echo "HTTP Status: $STATUS"
+               if [ "$STATUS" -ne 200 ]; then
+                 echo "Health check failed!"
+                exit 1
+               fi
 
 
 
